# Generated by Django 3.2 on 2021-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='Address',
        ),
        migrations.AddField(
            model_name='forms',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='Purpose',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
